/* oxlint-disable react/only-export-components -- icon lookup intentionally exports one constant */
import {
  Activity,
  AppWindow,
  BellRing,
  BookOpen,
  Box,
  Boxes,
  Briefcase,
  Building2,
  CalendarDays,
  ChartColumn,
  ChartLine,
  ChartPie,
  Cloud,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Eye,
  Fingerprint,
  FolderGit2,
  Gauge,
  Globe,
  HardDrive,
  Heart,
  KeyRound,
  Landmark,
  Layers,
  LifeBuoy,
  Lock,
  MessagesSquare,
  Network,
  Package,
  Radio,
  Receipt,
  Rocket,
  Router,
  Server,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SquareKanban,
  SquareCheck,
  Target,
  Terminal,
  Users,
  UserPlus,
  Wifi,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Stored as icon-name strings in the DB; unknown names fall back to AppWindow.
const ICONS: Record<string, LucideIcon> = {
  Activity,
  AppWindow,
  BellRing,
  BookOpen,
  Box,
  Boxes,
  Briefcase,
  Building2,
  CalendarDays,
  ChartColumn,
  ChartLine,
  ChartPie,
  Cloud,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Eye,
  Fingerprint,
  FolderGit2,
  Gauge,
  Globe,
  HardDrive,
  Heart,
  KeyRound,
  Landmark,
  Layers,
  LifeBuoy,
  Lock,
  MessagesSquare,
  Network,
  Package,
  Radio,
  Receipt,
  Rocket,
  Router,
  Server,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SquareKanban,
  SquareCheck,
  Target,
  Terminal,
  Users,
  UserPlus,
  Wifi,
  Workflow,
  Zap,
};

export const ICON_OPTIONS = Object.keys(ICONS).sort();

export function AppIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? AppWindow;
  return <Icon className={className} aria-hidden="true" />;
}
